# Generated by Django 6.0.2 on 2026-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_variant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
