# Generated by Django 6.0.2 on 2026-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
