# Generated by Django 6.0.2 on 2026-02-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_type_car_category_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car',
            new_name='Fleet',
        ),
    ]
